
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dkf-dep--kyverno
  namespace: "argocd"
  annotations:
    ## applications in 'deploykf-dependencies' come first
    ## NOTE: in this group, each application has a separate wave to avoid conflicts due to webhooks
    argocd.argoproj.io/sync-wave: "12"
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: deploykf-dependencies
    app.kubernetes.io/part-of: "deploykf"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: "default"
  source:
    repoURL: "https://github.com/sunnyh1220/deployKF-examples"
    targetRevision: "main"
    path: "GENERATOR_OUTPUT/manifests/deploykf-dependencies/kyverno"
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values-overrides.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "kyverno"
  syncPolicy:
    syncOptions:
      ## kyverno will fail to sync if not using one of `Replace` or `ServerSideApply`
      ## https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users
      - ServerSideApply=true