########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:


########################################
## DEPENDENCY | kyverno
########################################
## as we reference the "kyverno" chart (https://kyverno.github.io/kyverno) in `dependencies` of Chart.yaml,
## we must indent our values under `kyverno:` in this file
kyverno:
  fullnameOverride: kyverno

  ## Kyverno feature flags
  features:

    ## Sets the webhook failurePolicy to ignore (for the "resource" webhook only)
    forceFailurePolicyIgnore:
      ## TODO: remove once kyverno correctly removes webhooks on uninstall
      ##       https://github.com/kyverno/kyverno/issues/8390
      enabled: true

  ## A pre-delete hook to remove all Kyverno webhooks from the cluster
  webhooksCleanup:
    ## NOTE: we disable this because it is not supported by Argo CD:
    ##       https://github.com/kyverno/kyverno/issues/8390
    enabled: false

  ## Cleanup cronjobs to prevent internal resources from stacking up in the cluster
  cleanupJobs:

    admissionReports:
      enabled: true
      schedule: "*/10 * * * *"
      threshold: 10000
      image:
        registry: ""
        repository: "docker.io/bitnami/kubectl"
        pullPolicy: "IfNotPresent"

    clusterAdmissionReports:
      enabled: true
      schedule: "*/10 * * * *"
      threshold: 10000
      image:
        registry: ""
        repository: "docker.io/bitnami/kubectl"
        pullPolicy: "IfNotPresent"

  ## Admission controller configuration
  admissionController:
    replicas: ~
    initContainer:
      image:
        registry: ""
        repository: "ghcr.io/kyverno/kyvernopre"
        pullPolicy: "IfNotPresent"
    container:
      image:
        registry: ""
        repository: "ghcr.io/kyverno/kyverno"
        pullPolicy: "IfNotPresent"
    rbac:
      clusterRole:
        extraResources: []

  ## Background controller configuration
  backgroundController:
    enabled: true
    replicas: ~
    image:
      registry: ""
      repository: "ghcr.io/kyverno/background-controller"
      pullPolicy: "IfNotPresent"
    rbac:
      clusterRole:
        extraResources:
          - apiGroups: [""]
            resources: ["services"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          - apiGroups: ["apps"]
            resources: ["deployments"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          - apiGroups: ["security.istio.io"]
            resources: ["authorizationpolicies"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          - apiGroups: ["networking.istio.io"]
            resources: ["destinationrules"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          - apiGroups: ["apps"]
            resources: ["statefulsets"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          - apiGroups: ["kubeflow.org"]
            resources: ["poddefaults"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  ## Cleanup controller configuration
  cleanupController:
    enabled: true
    replicas: ~
    image:
      registry: ""
      repository: "ghcr.io/kyverno/cleanup-controller"
      pullPolicy: "IfNotPresent"
    rbac:
      clusterRole:
        extraResources:
          - apiGroups: [""]
            resources: ["services"]
          - apiGroups: ["apps"]
            resources: ["deployments"]
          - apiGroups: ["security.istio.io"]
            resources: ["authorizationpolicies"]
          - apiGroups: ["networking.istio.io"]
            resources: ["destinationrules"]
          - apiGroups: ["apps"]
            resources: ["statefulsets"]
          - apiGroups: ["kubeflow.org"]
            resources: ["poddefaults"]

  ## Reports controller configuration
  reportsController:
    enabled: true
    replicas: ~
    image:
      registry: ""
      repository: "ghcr.io/kyverno/reports-controller"
      pullPolicy: "IfNotPresent"
    rbac:
      clusterRole:
        extraResources: []